name: First app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_KEY }}
      - run: docker build -t project .
      - run: docker run -e CI=true project python manage.py test 
  
      - name: generated zip file
        run:   zip -r deploy.zip . -x '*.git*'
  
      - name: Deploy to EB
        uses:  einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker
          environment_name: docker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-864899847186 
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip        
          
